"""empty message

Revision ID: 89f404fb8f4a
Revises: 1972a0b5887e
Create Date: 2022-03-30 21:58:58.520653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89f404fb8f4a'
down_revision = '1972a0b5887e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'title')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
