"""empty message

Revision ID: 9b5d0ca6704a
Revises: 6cba466de7ac
Create Date: 2022-06-18 14:31:39.193350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5d0ca6704a'
down_revision = '6cba466de7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=True),
    sa.Column('phonetic', sa.String(length=120), nullable=True),
    sa.Column('mandarin', sa.String(length=120), nullable=True),
    sa.Column('phoneticM', sa.String(length=120), nullable=True),
    sa.Column('images', sa.String(length=120), nullable=True),
    sa.Column('part_of_speech', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    # ### end Alembic commands ###
